### ISSUE TITLE
Documentation is missing :(

### ISSUE THREAD

**Issue by gbrennon** [evojam/play-mongodb-driver#1]
Hey evojam team!

I'm starting to study Scala and Play framework and want to use your play-mongodb-driver but it seems it is lacking of documentation.

Do you have some doc written or something that I could be studying?

In case you can give me some tips about using this driver, I'll be writing docs for you :)
## EDIT

Reading scala-mongodb-driver i noticed that the examples are similar.

So the same code that I would use with pure Scala, I can use with this driver?

If yes, sorry for the issue :(

**Comment by gbrennon** [comment]
Reading scala-mongodb-driver i noticed that the examples are similar.

So the same code that I would use with pure Scala, I can use with this driver?

If yes, sorry for the issue :(

**Comment by albsadowski** [comment]
Hi @gbrennon,

unfortunately we don't have any docs yet. We plan to write some scaladoc soon. You can find some examples of how to use the driver here: http://evojam.com/blog/2015/6/15/async-mongodb-driver-for-scala-open-source-by-evojam.

`scala-mongodb-driver` is a different thing - it's a driver written by MongoDB team. The driver on which is based our `play-mongodb-driver` is https://github.com/evojam/mongodb-driver-scala.

**Comment by gbrennon** [comment]
In the link you posted there is only 1 example of how to use the driver :(

This lack of documentation is making me give up for now Scala + this MongoDB driver/ORM :(

**Comment by oscar-g** [comment]
Thanks so much for the async driver and the play implementation; it's worked great so far. Well...the parts I've figured out have worked great.

I'm getting stuck on formatters for ObjectId and BsonBinary.

I'd like to contribute to the docs. @dumpstate any plans for thorough documentation?

**Comment by WojciechP** [comment]
Hi @gbrennon and @oscar-g ,
apologies for such a late response.
Considering the current MongoDB landscape, we decided to drop the support for both https://github.com/evojam/mongodb-driver-scala and https://github.com/evojam/play-mongodb-driver. Since you both use Playframework, check out the https://github.com/ReactiveMongo/Play-ReactiveMongo - it provides a good integration out of the box.

Good luck with your applications ;)
